### ISSUE TITLE
Conflict with WSL

### ISSUE THREAD

**Issue by gucong3000** [imachug/win-sudo#13]
When i use [Windows Subsystem for Linux](https://msdn.microsoft.com/commandline/wsl/about)
The `sudo` command is broken.

**Comment by purplesyringa** [comment]
TBH, it wasn't intended to work on WSL. Have you tried whether it works with your fix?

**Comment by DemonixCraft** [comment]
I can use 'sudo' on WSL just fine

**Comment by gucong3000** [comment]
> it wasn't intended to work on WSL.

What I mean is that it accidentally affected WSL.

**Comment by gucong3000** [comment]
Several Linux distributions in the Microsoft Store.
I don't really remember which one is broken.
I will try to use Debian to reproduce this problem.

**Comment by purplesyringa** [comment]
Oh, I see. I've merged your PR, anyways.
