### ISSUE TITLE
cannot use sudo or su when home dir name contains space

### ISSUE THREAD

**Issue by DemianTinkiel** [imachug/win-sudo#2]
```
DemianTinkiel+Demian Tinkiel@DemianTinkiel MINGW64 ~/bin
$ sudo sh
realpath: Tinkiel/bin: No such file or directory
```

**Comment by purplesyringa** [comment]
Thank you for this report, I'll try to find how to fix this. By the way, `su` is equal to `sudo bash`, and it also allows you to create `~/.sudorc`.

**Comment by purplesyringa** [comment]
I've added some quotes - try now, please.

**Comment by DemianTinkiel** [comment]
Hi, thanks for that. Works now 👍

**Comment by AlokBhushanJss** [comment]
I am having this same problem. how to add quotes?

**Comment by purplesyringa** [comment]
@AlokBhushanJss Looks like that is a separate problem. The quotes were committed already. Please fill in a new issue.

Does this happen with `sudo` or `su`? `su`, unlike Linux, is an alias for `sudo bash` (and loading ~/.sudorc if it exists).
