### ISSUE TITLE
Can't use in git bash windows

### ISSUE THREAD

**Issue by evanmartua34** [imachug/win-sudo#27]
![image](https://user-images.githubusercontent.com/40655866/42154927-2f54f5a8-7e11-11e8-93cc-37c9ae5990db.png)

i follow all step but still can't use sudo in git for windows

**Comment by purplesyringa** [comment]
Oh, I'm sorry that the instructions are a bit outdated. You need to add /c/Users/User/win-sudo/s to PATH instead.

Feel free to reopen if you have problems.
