### ISSUE TITLE
sudo on nano freezes

### ISSUE THREAD

**Issue by tuguldurio** [imachug/win-sudo#34]
in git-bash when i write `$ sudo nano sometext.txt` it freezes

**Comment by purplesyringa** [comment]
Can you see Windows asking you for admin credentinals (User Account Control)? Does it hang on other commands like `sudo echo 1` or `su`?

**Comment by tuguldurio** [comment]
earlier a day other than that was working, but now it gives `UAC elevation was canceled`

**Comment by purplesyringa** [comment]
Is powershell installed on your system? Is, by any chance, UAC is disabled at all (i.e. you can run programs as administrator without Windows asking you for password/pressing `Yes`)?

**Comment by purplesyringa** [comment]
@tuguldurio

**Comment by tuguldurio** [comment]
For some strange reason its working now, maybe it had something to do with my UAC.

**Comment by purplesyringa** [comment]
Great to hear this problem is solved.
