### ISSUE TITLE
sudo and su doesn't respond to any commands

### ISSUE THREAD

**Issue by BlackOfWorld** [imachug/win-sudo#4]
<img width="103" alt="screenshot_1" src="https://user-images.githubusercontent.com/16164933/35742000-90d0b78e-0839-11e8-89d9-4b4675747cd1.png">

**Comment by purplesyringa** [comment]
Did UAC elevation window appear?

**Comment by BlackOfWorld** [comment]
Yes, it did.

**Comment by purplesyringa** [comment]
What happens when you run:

```
powershell.exe Start-Process "cmd" -Verb RunAs
```

in cmd?

**Comment by BlackOfWorld** [comment]
UAC elevation window opens, I clicked yes, and then it opens an elevated cmd.

**Comment by purplesyringa** [comment]
Okay, wait a minute, I'll add a testing branch.

**Comment by purplesyringa** [comment]
I've created `testing` branch - please fetch and try again.

**Comment by BlackOfWorld** [comment]
I tried, but same results. I don't receive any output.

**Comment by purplesyringa** [comment]
You should have received some error messages. Are you sure you are running correct `sudo`?

**Comment by BlackOfWorld** [comment]
I noticed that the installer doesn't download sudobackend. I downloaded that file and now it works.

**Comment by purplesyringa** [comment]
I'll add downloading sudobackend to the installer, thank you for report!

**Comment by purplesyringa** [comment]
@BlackOfWorld Also make sure to download `sudorc`.

**Comment by purplesyringa** [comment]
I've posted the fix.
