### ISSUE TITLE
commands with sudo hang, su hangs

### ISSUE THREAD

**Issue by michaelchanwork** [imachug/win-sudo#44]
After some fixes/handling of spaces in https://github.com/imachug/win-sudo/pull/43 (Which I can't test to have worked without the fixes, and currently believe the issue to be unrelated to aforementioned fixes)

Running su or sudo *any command*
the terminal will simply hang indefinitely, though I am still able to ctrl+c out.

Windows 10, version 1909
```
$ bash --version
bash --version
GNU bash, version 4.4.23(1)-release (x86_64-pc-msys)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by neveratdennys** [comment]
I understand the issue with user name with spaces that is already fixed (which is true for my case), but I'm still having the same issue with su hanging after windows prompts for admin permissions. This is a really cool project regardless though, hopefully this can be fixed.

**Comment by riedel** [comment]
may this be the same problem as #36? It works for me inside mintty (using a pty) but not e.g. windows terminal (unsing the windows console)

**Comment by riedel** [comment]
Fixed in 5b2d65b4d38ee612598fa94980dacfa6e64b79c7 ?

**Comment by neveratdennys** [comment]
Just verified and looks like it's working for me now. Thanks!

**Comment by purplesyringa** [comment]
Thanks for the fix again!
