### ISSUE TITLE
powershell.exe : command not found.

### ISSUE THREAD

**Issue by vishaaaal-droid** [imachug/win-sudo#45]
When I run sudo command in my bash terminal, it throws this error.

```
/c/Users/User/bin/win-sudo/s/sudo: line 74: powershell.exe: command not found
UAC elevation was canceled
```
This is the line 74.

`if ! powershell.exe Start-Process \""$(cygpath -w /bin/)"bash\" \""$backend"\", \"$fifoid\" -Verb RunAs -WorkingDirectory \"\$PWD\" -WindowStyle Hidden\; \(\$Error[0]\).InvocationInfo.Line; then
`
What should I do?

**Comment by purplesyringa** [comment]
What Windows version are you using?

**Comment by vishaaaal-droid** [comment]
Windows 7

**Comment by vishaaaal-droid** [comment]
So, I may need to install powershell , :sweat_smile:

**Comment by purplesyringa** [comment]
Yeah, IIRC some old Windows 7 versions don't have PowerShell by default. Try installing it
