### ISSUE TITLE
How to uninstall it?

### ISSUE THREAD

**Issue by willsoares** [imachug/win-sudo#47]
I find didn't had much succest with it, so i want to undo the changes made. Is there an easy way to do it?

**Comment by purplesyringa** [comment]
1. Delete directory `~/bin/win-sudo`.
2. Delete the line saying `[ -f ".../bin/win-sudo/s/path.sh" ] && source ".../bin/win-sudo/s/path.sh"` from `~/.bashrc` or `~/.bash_profile` (not sure which file contains that line -- maybe both).

Hope that helps.
